const featuredProjects = [
  {
    id: 'agrobridge',
    title: 'AgroBridge',
    badge: 'SIH 2026 Finalist',
    tagline: 'AI-Powered Market Intelligence for Farmers',
    description: 'An AI-driven decision engine for farmers, providing real-time price forecasting, "Sell/Wait" recommendations, and smart buyer matching to maximize net realization. Built for Smart India Hackathon 2026.',
    tech: ['React', 'Python', 'FastAPI', 'XGBoost', 'SHAP', 'Groq API', 'GitHub Actions', 'Tailwind CSS'],
    github: 'https://github.com/harshm13/AgroBridge-SIH26132',
    demo: 'https://agro-bridge-sih-26132.vercel.app',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&q=80',
    stats: { stars: '0', status: 'SIH 2026 Finalist' },
    glow: 'from-emerald-600/30 via-green-600/20 to-teal-600/30',
  },
  {
    id: 'globetrotter',
    title: 'GlobeTrotter',
    badge: 'Odoo x LDCE Hackathon',
    tagline: 'Global Exploration & Travel Planning',
    description: 'Developed under tight deadlines for the Odoo x LDCE Hackathon (Team NexusVoid). GlobeTrotter is an innovative application designed to streamline global exploration and travel planning. Engineered with a focus on rapid deployment, clean UI/UX, and scalable architecture.',
    tech: ['React', 'Node.js', 'Tailwind CSS', 'Vite'],
    github: 'https://github.com/harshm13/GlobeTrotter-NexusVoid',
    demo: 'https://github.com/harshm13/GlobeTrotter-NexusVoid',
    image: 'https://images.unsplash.com/photo-1542224566-6e85f2e6772f?auto=format&fit=crop&w=1920&q=80',
    stats: { stars: '0', status: 'Hackathon Build' },
    glow: 'from-orange-600/30 via-amber-600/20 to-yellow-600/30',
  },
  {
    id: 'greenroute',
    title: 'GreenRoute',
    badge: 'Smart Waste Management',
    tagline: 'Gamified Recycling & Optimized Fleet Routing',
    description: 'An IoT-inspired smart waste management platform featuring a gamified citizen app for recycling rewards and a map-based admin dashboard for optimized fleet routing. Reduces fuel consumption through dynamic priority routing and predictive heatmaps.',
    tech: ['HTML5', 'CSS3', 'JavaScript', 'Leaflet.js', 'SweetAlert2', 'Particles.js', 'Python', 'FastAPI', 'MongoDB'],
    github: 'https://github.com/harshm13/green_route_project',
    demo: 'https://github.com/harshm13/green_route_project',
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1600&q=80',
    stats: { stars: '0', status: 'In Active Development' },
    glow: 'from-green-600/30 via-emerald-600/20 to-teal-600/30', // Fixed: Moved this here from the stray line below
  },
  {
    id: 'resumeos',
    title: 'ResumeOS',
    badge: 'AI SaaS Platform',
    tagline: 'Next-Gen AI Resume Builder & Career OS',
    description: 'Architecting an enterprise-grade resume platform with real-time ATS scoring, AI bullet enhancement, and split-screen live previews. Currently finalizing the Node.js backend integration.',
    tech: ['React', 'Node.js', 'Express', 'Tailwind v4', 'Gemini API'],
    github: 'https://github.com/harshm13/ResumeOS',
    demo: 'https://github.com/harshm13/ResumeOS',
    image: '/resumeos-thumb.svg',
    stats: { stars: '0', status: 'In Active Development' },
    glow: 'from-blue-600/30 via-cyan-600/20 to-indigo-600/30',
  },
  {
    id: 'nexusvoid',
    title: 'Codex AI – NexusVoid',
    badge: 'Featured AI SaaS',
    tagline: 'Autonomous AI-Powered Developer Platform',
    description: 'An advanced AI coding assistant platform featuring prompt management, real-time conversation history, zero-key resilience, live code execution previews, and unified diff/patch code generation.',
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'Gemini API', 'Tailwind CSS'],
    github: 'https://github.com/harshm13/NexusVoid',
    demo: 'https://codexai-nine.vercel.app/',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    stats: { stars: '14', status: 'Live Production' },
    glow: 'from-blue-600/30 via-indigo-600/20 to-purple-600/30',
  },
  {
    id: 'transitops',
    title: 'TransitOps',
    badge: 'Enterprise Platform',
    tagline: 'Fleet Management & Route Operations System',
    description: 'Developing a comprehensive transportation management solution featuring real-time driver analytics dashboards, route scheduling, and operational efficiency tools. Backend architecture is currently underway.',
    tech: ['React', 'Node.js', 'MongoDB', 'REST APIs', 'Tailwind CSS'],
    github: 'https://github.com/harshm13/TransitOps',
    demo: 'https://github.com/harshm13/TransitOps',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    stats: { stars: '9', status: 'Building Backend' },
    glow: 'from-cyan-600/30 via-blue-600/20 to-teal-600/30',
  },
  {
    id: 'lifesaver',
    title: 'The Last-Minute Life Saver',
    badge: 'AI Productivity',
    tagline: 'Intelligent AI Task Prioritizer',
    description: 'An AI-driven productivity suite for urgent task breakdown, automated schedule optimization, and smart deadline reminders. Currently in local beta testing for the prompt engineering logic.',
    tech: ['React', 'OpenAI API', 'Node.js', 'Framer Motion', 'Tailwind CSS'],
    github: 'https://github.com/harshm13/LastMinuteLifeSaver',
    demo: 'https://github.com/harshm13/LastMinuteLifeSaver',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=800&q=80',
    stats: { stars: '11', status: 'Beta (Local Testing)' },
    glow: 'from-purple-600/30 via-pink-600/20 to-rose-600/30',
  },
  {
    id: 'projectatlas',
    title: 'Project Atlas',
    badge: 'Personal Portfolio',
    tagline: 'Futuristic AI-Inspired Portfolio Website',
    description: 'The flagship personal portfolio for Harsh Mehta built with React, Vite, Tailwind CSS, Framer Motion, and GitHub API integrations. Designed with glassmorphism and 60FPS dynamic particle mesh.',
    tech: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion', 'GitHub API'],
    github: 'https://github.com/harshm13/ProjectAtlas',
    demo: '#home',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    stats: { stars: '8', status: 'V2.6 Live' },
    glow: 'from-accent/30 via-primary/20 to-secondary/30',
  },
];
